#!/bin/sh
# Renders the Homebrew formula for the SpecHarbor tap (guferreira1/homebrew-tap).
#
# Emits a macOS formula (Apple Silicon and Intel) that installs the prebuilt
# specharbor binary from the official GitHub Release for the given version and
# pins each download to its SHA-256 from the release checksums.txt. The formula
# is printed to stdout; this script does not write files, push commits, access
# the network, or print secrets.
#
# Usage:
#   scripts/render-homebrew-formula.sh --version X.Y.Z --checksums <checksums.txt>
#
# The version must be plain X.Y.Z; the release tag is vX.Y.Z.

set -eu

VERSION=""
CHECKSUMS=""

fail() {
    printf 'render-homebrew-formula: %s\n' "$1" >&2
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --version)
            shift
            [ $# -gt 0 ] || fail '--version requires a value'
            VERSION="$1"
            ;;
        --checksums)
            shift
            [ $# -gt 0 ] || fail '--checksums requires a value'
            CHECKSUMS="$1"
            ;;
        *)
            fail "unknown argument: $1"
            ;;
    esac
    shift
done

[ -n "${VERSION}" ] || fail 'missing --version'
[ -n "${CHECKSUMS}" ] || fail 'missing --checksums'
printf '%s' "${VERSION}" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' ||
    fail "version \"${VERSION}\" is not a plain X.Y.Z version"
[ -f "${CHECKSUMS}" ] || fail "checksums file not found: ${CHECKSUMS}"

TAG="v${VERSION}"
DOWNLOAD_BASE="https://github.com/guferreira1/spec-harbor/releases/download/${TAG}"

# checksums.txt lines are "<sha256>  <asset>" (GoReleaser sha256 format).
sha_for() {
    asset="$1"
    value="$(awk -v name="${asset}" '$2 == name { print $1; exit }' "${CHECKSUMS}")"
    [ -n "${value}" ] || fail "no checksum entry for ${asset} in ${CHECKSUMS}"
    printf '%s' "${value}"
}

ARM_ASSET="specharbor_Darwin_arm64.tar.gz"
INTEL_ASSET="specharbor_Darwin_x86_64.tar.gz"
ARM_SHA="$(sha_for "${ARM_ASSET}")"
INTEL_SHA="$(sha_for "${INTEL_ASSET}")"

cat <<EOF
# This formula is generated by scripts/render-homebrew-formula.sh in
# guferreira1/spec-harbor. Do not edit it by hand.
class Specharbor < Formula
  desc "Spec-driven workflow CLI for AI coding agents"
  homepage "https://github.com/guferreira1/spec-harbor"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${DOWNLOAD_BASE}/${ARM_ASSET}"
      sha256 "${ARM_SHA}"
    end
    on_intel do
      url "${DOWNLOAD_BASE}/${INTEL_ASSET}"
      sha256 "${INTEL_SHA}"
    end
  end

  def install
    bin.install "specharbor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/specharbor version")
  end
end
EOF
